In [2]:
import pandas as pd
import numpy as np

In [13]:
df1=pd.DataFrame(np.random.randn(3,3),index=list('abc'),columns=list('ABC')) #标准正态分布
df1

A         B         C
a -0.661608 -1.737274 -0.577280
b  0.068244  0.527712  0.618131
c  0.689902  0.243183  0.796401

In [14]:
dic1={'name':['张三','李四','王二麻子','小淘气'],'age':[37,30,50,16],'gender':['男','男','男','女']}
dic1

{'name': ['张三', '李四', '王二麻子', '小淘气'],
 'age': [37, 30, 50, 16],
 'gender': ['男', '男', '男', '女']}

In [15]:
df5=pd.DataFrame(dic1)
print(df5)

   name  age gender
0    张三   37      男
1    李四   30      男
2  王二麻子   50      男
3   小淘气   16      女


In [16]:
df5.dtypes

name      object
age        int64
gender    object
dtype: object

In [18]:
#只有head/tail要括号
print(df5.head())
print(df5.head(2))
print(df5.tail())
print(df5.tail(2))

   name  age gender
0    张三   37      男
1    李四   30      男
2  王二麻子   50      男
3   小淘气   16      女
  name  age gender
0   张三   37      男
1   李四   30      男
   name  age gender
0    张三   37      男
1    李四   30      男
2  王二麻子   50      男
3   小淘气   16      女
   name  age gender
2  王二麻子   50      男
3   小淘气   16      女


In [20]:
print(df5.index)
print(df5.columns)
print(df5.values)

RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'gender'], dtype='object')
[['张三' 37 '男']
 ['李四' 30 '男']
 ['王二麻子' 50 '男']
 ['小淘气' 16 '女']]


In [26]:
df6=pd.DataFrame(np.arange(36).reshape(6,6),index=list('abcdef'), columns=list('ABCDEF'))
df6

A   B   C   D   E   F
a   0   1   2   3   4   5
b   6   7   8   9  10  11
c  12  13  14  15  16  17
d  18  19  20  21  22  23
e  24  25  26  27  28  29
f  30  31  32  33  34  35

In [58]:
print(df6.values)
print(df6['B'].values)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 1  7 13 19 25 31]


In [43]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [46]:
np.arange(0,60,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [52]:
df=pd.DataFrame(np.arange(0,60,2).reshape(10,3),columns=list('abc'))
df

a   b   c
0   0   2   4
1   6   8  10
2  12  14  16
3  18  20  22
4  24  26  28
5  30  32  34
6  36  38  40
7  42  44  46
8  48  50  52
9  54  56  58

条件筛选

In [53]:
df[df['a']>30]

a   b   c
6  36  38  40
7  42  44  46
8  48  50  52
9  54  56  58

In [56]:
print(df[['b','c']])
print(df[['b','c']][df['a']>30])

    b   c
0   2   4
1   8  10
2  14  16
3  20  22
4  26  28
5  32  34
6  38  40
7  44  46
8  50  52
9  56  58
    b   c
6  38  40
7  44  46
8  50  52
9  56  58


In [57]:
df[df.a.isin([30,54])]

a   b   c
5  30  32  34
9  54  56  58

In [62]:
df[(df['a']>30)&(df['b']>40)]

a   b   c
7  42  44  46
8  48  50  52
9  54  56  58

In [63]:
df[np.logical_and(df['a']>30,df['b']>40)]

a   b   c
7  42  44  46
8  48  50  52
9  54  56  58

排除特定行

基本做法是将a列出来，把值30和54剔除，再使用isin函数

In [70]:
ex_list=list(df['a'])
ex_list

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54]

In [71]:
ex_list.remove(30)
ex_list.remove(54)

In [72]:
ex_list

[0, 6, 12, 18, 24, 36, 42, 48]

In [73]:
df[df.a.isin(ex_list)]

a   b   c
0   0   2   4
1   6   8  10
2  12  14  16
3  18  20  22
4  24  26  28
6  36  38  40
7  42  44  46
8  48  50  52

索引筛选

In [74]:
df[1:4]

a   b   c
1   6   8  10
2  12  14  16
3  18  20  22

In [76]:
df[['a','c']]

a   c
0   0   4
1   6  10
2  12  16
3  18  22
4  24  28
5  30  34
6  36  40
7  42  46
8  48  52
9  54  58

In [77]:
df.loc[0,'c']

4

In [78]:
df.loc[1:4,['a','c']]

a   c
1   6  10
2  12  16
3  18  22
4  24  28

In [79]:
df.loc[[1,3,5],['a','c']]

a   c
1   6  10
3  18  22
5  30  34

In [80]:
df.iloc[0,2]

4

In [81]:
df.iloc[1:4,[0,2]]

a   c
1   6  10
2  12  16
3  18  22

In [82]:
df.iloc[[1,3,5],[0,2]]

a   c
1   6  10
3  18  22
5  30  34

In [83]:
df.iloc[[1,3,5],0:2]

a   b
1   6   8
3  18  20
5  30  32

IX

ix的功能更加强大，参数既可以是索引，也可以是名称，相当于，loc和iloc的合体。需要注意的是在使用的时候需要统一，在行选择时同时出现索引和名称， 同样在同行选择时同时出现索引和名称

In [85]:
df.ix[1:3,['a','b']]

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


a   b
1   6   8
2  12  14
3  18  20

In [86]:
df.ix[[1,3,5],['a','b']]

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


a   b
1   6   8
3  18  20
5  30  32

In [87]:
df.ix[[1,3,5],[0,2]]

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


a   c
1   6  10
3  18  22
5  30  34

In [88]:
df.at[3,'a']

18

In [89]:
df.iat[3,0]

18

DataFrame操作

In [92]:
df6=pd.DataFrame(np.arange(36).reshape(6,6),index=list('abcdef'), columns=list('ABCDEF'))
df6

A   B   C   D   E   F
a   0   1   2   3   4   5
b   6   7   8   9  10  11
c  12  13  14  15  16  17
d  18  19  20  21  22  23
e  24  25  26  27  28  29
f  30  31  32  33  34  35

In [95]:
df6.T

a   b   c   d   e   f
A  0   6  12  18  24  30
B  1   7  13  19  25  31
C  2   8  14  20  26  32
D  3   9  15  21  27  33
E  4  10  16  22  28  34
F  5  11  17  23  29  35

根据列进行描述性统计

In [94]:
df6.describe()

A          B          C          D          E          F
count   6.000000   6.000000   6.000000   6.000000   6.000000   6.000000
mean   15.000000  16.000000  17.000000  18.000000  19.000000  20.000000
std    11.224972  11.224972  11.224972  11.224972  11.224972  11.224972
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000
25%     7.500000   8.500000   9.500000  10.500000  11.500000  12.500000
50%    15.000000  16.000000  17.000000  18.000000  19.000000  20.000000
75%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000
max    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000

sum默认每列求和，sum(1)对每行求和

In [96]:
df6.sum()

A     90
B     96
C    102
D    108
E    114
F    120
dtype: int64

In [97]:
df6.sum(1)

a     15
b     51
c     87
d    123
e    159
f    195
dtype: int64

匿名函数lambda

lambda x,y:x*y       #x,y为输入,x*y为输出

lambda *args:sum(args)  # 函数输入为任意个数的参数，输出是它们的和(隐性要求输入参数必须能够进行加法运算)

lambda **kwargs:5     # 输入为任意键值对参数，输出为5

In [100]:
df6.apply(lambda x:x*2)

A   B   C   D   E   F
a   0   2   4   6   8  10
b  12  14  16  18  20  22
c  24  26  28  30  32  34
d  36  38  40  42  44  46
e  48  50  52  54  56  58
f  60  62  64  66  68  70

In [103]:
df6['G']=['999','999','999','999','999','999']
df6

A   B   C   D   E   F    G
a   0   1   2   3   4   5  999
b   6   7   8   9  10  11  999
c  12  13  14  15  16  17  999
d  18  19  20  21  22  23  999
e  24  25  26  27  28  29  999
f  30  31  32  33  34  35  999

In [107]:
df6.insert(0,'QQ',['999','999','999','999','999','999'])
df6

QQ   A   B   C   D   E   F    G
a  999   0   1   2   3   4   5  999
b  999   6   7   8   9  10  11  999
c  999  12  13  14  15  16  17  999
d  999  18  19  20  21  22  23  999
e  999  24  25  26  27  28  29  999
f  999  30  31  32  33  34  35  999

In [113]:
df7=pd.DataFrame(['my','name','is','a','b','c'],index=list('abcdef'),columns=list('H'))
df7

H
a    my
b  name
c    is
d     a
e     b
f     c

join根据列名合并

In [115]:
df8=df6.join(df7)
df8

QQ   A   B   C   D   E   F    G     H
a  999   0   1   2   3   4   5  999    my
b  999   6   7   8   9  10  11  999  name
c  999  12  13  14  15  16  17  999    is
d  999  18  19  20  21  22  23  999     a
e  999  24  25  26  27  28  29  999     b
f  999  30  31  32  33  34  35  999     c

In [117]:
df7 = pd.DataFrame(['2', '6', '7', '19', '44', '77'], index=list('abekld'), columns=list('I'))
df7

I
a   2
b   6
e   7
k  19
l  44
d  77

In [118]:
df8=df6.join(df7,how='inner')
df9=df6.join(df7,how='outer')

In [119]:
print(df8)

    QQ   A   B   C   D   E   F    G   I
a  999   0   1   2   3   4   5  999   2
b  999   6   7   8   9  10  11  999   6
d  999  18  19  20  21  22  23  999  77
e  999  24  25  26  27  28  29  999   7


In [120]:
print(df9)

    QQ     A     B     C     D     E     F    G    I
a  999   0.0   1.0   2.0   3.0   4.0   5.0  999    2
b  999   6.0   7.0   8.0   9.0  10.0  11.0  999    6
c  999  12.0  13.0  14.0  15.0  16.0  17.0  999  NaN
d  999  18.0  19.0  20.0  21.0  22.0  23.0  999   77
e  999  24.0  25.0  26.0  27.0  28.0  29.0  999    7
f  999  30.0  31.0  32.0  33.0  34.0  35.0  999  NaN
k  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   19
l  NaN   NaN   NaN   NaN   NaN   NaN   NaN  NaN   44


concat合并多个DataFrame

In [121]:
df10 = pd.DataFrame([1, 2, 3, 4, 5, 6], 
					index=list('ABCDEF'), columns=['a'])
df11 = pd.DataFrame([10, 20, 30, 40, 50, 60],
                    index=list('ABCDEF'), columns=['b'])
df12 = pd.DataFrame([100, 200, 300, 400, 500, 600],
                    index=list('ABCDEF'), columns=['c'])
list1 = [df10.T, df11.T, df12.T]
df13 = pd.concat(list1)
print(df13)

     A    B    C    D    E    F
a    1    2    3    4    5    6
b   10   20   30   40   50   60
c  100  200  300  400  500  600


去重

df.drop_duplicates(subset=None,
                   keep='first',
                   inplace=False
                   )
参数：

subset：指定是哪些列重复。
keep：去重后留下第几行，{‘first’, ‘last’, False}, default ‘first’｝，如果是False，则去除全部重复的行。
inplace：是否作用于原来的df。

In [124]:
df14=pd.DataFrame(data=[[1,2,3],[1,2,4],[1,2,4],[1,2,3],[1,2,5],[1,2,5]],index=list('ABCDEF'),columns=['a','b','c'])
df14

a  b  c
A  1  2  3
B  1  2  4
C  1  2  4
D  1  2  3
E  1  2  5
F  1  2  5

In [125]:
df14.drop_duplicates(keep='last')

a  b  c
C  1  2  4
D  1  2  3
F  1  2  5

In [126]:
print(df14.drop_duplicates(subset=('c',)))

   a  b  c
A  1  2  3
B  1  2  4
E  1  2  5


numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

在指定的间隔内返回均匀间隔的数字

返回num均匀分布的样本，在[start, stop]

In [127]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [128]:
np.linspace(1,10,endpoint=False)

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

In [129]:
np.linspace(1,10,endpoint=False,retstep=True)

(array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
        2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
        4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
        6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
        8.92, 9.1 , 9.28, 9.46, 9.64, 9.82]), 0.18)

In [3]:
data={'one':np.random.randn(4),'two':np.linspace(1,4,4),'three':['zhangsan','李四',999,0.1]}

In [4]:
data

{'one': array([-1.08171784, -2.63044892,  0.33151667,  0.4620326 ]),
 'two': array([1., 2., 3., 4.]),
 'three': ['zhangsan', '李四', 999, 0.1]}

In [6]:
df=pd.DataFrame(data,index=[1,2,3,4])
df

one  two     three
1 -1.081718  1.0  zhangsan
2 -2.630449  2.0        李四
3  0.331517  3.0       999
4  0.462033  4.0       0.1

df创建完成好可以重新设置索引，通常用到3个函数：set_index、reset_index、reindex

set _index用于将df中的一行或多行设置为索引。

df.set_index(['one'],drop=False) ordf.set_index('one')

df.set_index(['one','two'])

参数drop默认为True，意为将该列设置为索引后从数据中删除，如果设为False，将继续在数据中保留该行。

In [8]:
dataset=df
dataset.set_index('one')

two     three
one                     
-1.081718  1.0  zhangsan
-2.630449  2.0        李四
 0.331517  3.0       999
 0.462033  4.0       0.1

In [9]:
dataset=df
dataset.set_index('one',drop=False)

one  two     three
one                               
-1.081718 -1.081718  1.0  zhangsan
-2.630449 -2.630449  2.0        李四
 0.331517  0.331517  3.0       999
 0.462033  0.462033  4.0       0.1

In [10]:
dataset=df
dataset.set_index(['one'],drop=False)

one  two     three
one                               
-1.081718 -1.081718  1.0  zhangsan
-2.630449 -2.630449  2.0        李四
 0.331517  0.331517  3.0       999
 0.462033  0.462033  4.0       0.1

In [12]:
df.index=['a','b','c','d']
df

one  two     three
a -1.081718  1.0  zhangsan
b -2.630449  2.0        李四
c  0.331517  3.0       999
d  0.462033  4.0       0.1

In [13]:
df1=df
df1.reset_index()

index       one  two     three
0     a -1.081718  1.0  zhangsan
1     b -2.630449  2.0        李四
2     c  0.331517  3.0       999
3     d  0.462033  4.0       0.1

In [15]:
df1=df
df1.reset_index(drop=True)

one  two     three
0 -1.081718  1.0  zhangsan
1 -2.630449  2.0        李四
2  0.331517  3.0       999
3  0.462033  4.0       0.1

In [19]:
data=np.random.randn(6,4)
df=pd.DataFrame(data,columns=list('ABCD'),index=[1,2,'a','b','2006-10-1','第六行'])
df

A         B         C         D
1          1.107185  0.362097 -1.884317 -2.018558
2          0.014205  0.118368 -1.638143 -0.632581
a         -0.720219 -0.310075  2.395780 -0.851828
b          0.698468 -1.630131  0.423396  1.419592
2006-10-1 -0.486496 -1.353278 -1.006200  0.249347
第六行        1.447681  0.561854  0.808706 -1.324587

In [17]:
pd.DataFrame(columns=['id','name','grade','class'])

Empty DataFrame
Columns: [id, name, grade, class]
Index: []

方法1：df.列名
该方法每次只能读取一列

In [20]:
df.A

1            1.107185
2            0.014205
a           -0.720219
b            0.698468
2006-10-1   -0.486496
第六行          1.447681
Name: A, dtype: float64

方法2：df['列名']or df[['列名']]、df[['列名1','列名2','列名n']]

In [21]:
df[['A']]

A
1          1.107185
2          0.014205
a         -0.720219
b          0.698468
2006-10-1 -0.486496
第六行        1.447681

In [22]:
df[['A','C','D']]

A         C         D
1          1.107185 -1.884317 -2.018558
2          0.014205 -1.638143 -0.632581
a         -0.720219  2.395780 -0.851828
b          0.698468  0.423396  1.419592
2006-10-1 -0.486496 -1.006200  0.249347
第六行        1.447681  0.808706 -1.324587

In [23]:
df['A'][1]

1.1071853206978335

In [24]:
df.A[1]

1.1071853206978335

df.loc[row][col]或df.loc[row,col]

In [27]:
df.loc[1][['A','B']]

A    1.107185
B    0.362097
Name: 1, dtype: float64

In [28]:
df.loc[1,['A','B']]

A    1.107185
B    0.362097
Name: 1, dtype: float64

In [29]:
df.loc[1,'A':'C']

A    1.107185
B    0.362097
C   -1.884317
Name: 1, dtype: float64

In [35]:
df1.insert(2,'four',[11,22,33,44])
df1

one  two  four     three
a -1.081718  1.0    11  zhangsan
b -2.630449  2.0    22        李四
c  0.331517  3.0    33       999
d  0.462033  4.0    44       0.1

In [40]:
df1.reset_index(drop=True)

one  two  four     three
0 -1.081718  1.0    11  zhangsan
1 -2.630449  2.0    22        李四
2  0.331517  3.0    33       999
3  0.462033  4.0    44       0.1

In [42]:
row={'one':111,'two':222,'four':444,'three':333}
df1.iloc[0]=row
df1

one  two  four  three
a       one  two  four  three
b  -2.63045    2    22     李四
c  0.331517    3    33    999
d  0.462033    4    44    0.1

In [46]:
data1={'five':[1,34,67,100],'four':[1.05,-0.55,1.25,-1.53]}
df1=pd.DataFrame(data1,index=[1,2,3,4])
df1

five  four
1     1  1.05
2    34 -0.55
3    67  1.25
4   100 -1.53

In [48]:
data2={'one':[222,213],'three':['AAA','BBB'],'two':[11,22]}
df2=pd.DataFrame(data2)
df2

one three  two
0  222   AAA   11
1  213   BBB   22

按行合并

In [49]:
pd.concat([df1,df2],axis=1)

five  four    one three   two
0    NaN   NaN  222.0   AAA  11.0
1    1.0  1.05  213.0   BBB  22.0
2   34.0 -0.55    NaN   NaN   NaN
3   67.0  1.25    NaN   NaN   NaN
4  100.0 -1.53    NaN   NaN   NaN

按列合并

In [50]:
pd.concat([df1,df2],axis=0)

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


five  four    one three   two
1    1.0  1.05    NaN   NaN   NaN
2   34.0 -0.55    NaN   NaN   NaN
3   67.0  1.25    NaN   NaN   NaN
4  100.0 -1.53    NaN   NaN   NaN
0    NaN   NaN  222.0   AAA  11.0
1    NaN   NaN  213.0   BBB  22.0

In [51]:
df1.append(df2)

E:\anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


five  four    one three   two
1    1.0  1.05    NaN   NaN   NaN
2   34.0 -0.55    NaN   NaN   NaN
3   67.0  1.25    NaN   NaN   NaN
4  100.0 -1.53    NaN   NaN   NaN
0    NaN   NaN  222.0   AAA  11.0
1    NaN   NaN  213.0   BBB  22.0

In [54]:
df.drop(['A','B'],axis=1)

C         D
1         -1.884317 -2.018558
2         -1.638143 -0.632581
a          2.395780 -0.851828
b          0.423396  1.419592
2006-10-1 -1.006200  0.249347
第六行        0.808706 -1.324587

In [55]:
df.drop([1,'a'],axis=0)

A         B         C         D
2          0.014205  0.118368 -1.638143 -0.632581
b          0.698468 -1.630131  0.423396  1.419592
2006-10-1 -0.486496 -1.353278 -1.006200  0.249347
第六行        1.447681  0.561854  0.808706 -1.324587

In [59]:
df.pop('A')
df

B         C         D
1          0.362097 -1.884317 -2.018558
2          0.118368 -1.638143 -0.632581
a         -0.310075  2.395780 -0.851828
b         -1.630131  0.423396  1.419592
2006-10-1 -1.353278 -1.006200  0.249347
第六行        0.561854  0.808706 -1.324587

In [60]:
df.axes

[Index([1, 2, 'a', 'b', '2006-10-1', '第六行'], dtype='object'),
 Index(['B', 'C', 'D'], dtype='object')]

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 1 to 第六行
Data columns (total 3 columns):
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(3)
memory usage: 352.0+ bytes
